### ISSUE TITLE
Bring back Clarity CodeCov Table on PR Conversations

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#611]
**Is your feature request related to a problem? Please describe.**

Using Github Action we use to have a nice CodeCov tabled displayed on PRs conversations, not is not working. Bring it back!

We use to have something like this goodie:
![image](https://github.com/Trust-Machines/stacks-sbtc/assets/30682875/2ad05994-879f-4af2-bbc6-32f3928531e9)

**Describe the solution you'd like**

Review what happended with the GH Action and fix it.

**Describe alternatives you've considered**

There are many version of CodeCov GH module...

**Additional context**

There is a text only table but hidden in the actions outputs, inconvenient to find and look...

**Comment by friedger** [comment]
For clarity code there is a script `coverage-report.sh` to generate coverage data

**Comment by jo-tm** [comment]
yep, I think is also useful to see the coverage Delta on the PRs.

**Comment by jo-tm** [comment]
@AshtonStephens wants to track this effort.

**Comment by jo-tm** [comment]
@AshtonStephens any idea on how to fix this? I was using `https://github.com/Trust-Machines/stacks-sbtc/blob/main/.github/workflows/clarinet.yml` but something changed on another file and break it.

**Comment by AshtonStephens** [comment]
@friedger I've been looking at the clarity workflow for a bit and would prefer the workflow utilize the canonical method of adding clarinet testing in a CI (below) as opposed to what it does now.

```yaml
name: CI
on: [push]
jobs:
  tests:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Execute unit tests"
        uses: docker://hirosystems/clarinet:latest # <----- This bit
        with:
          args: test --coverage --manifest-path=./Clarinet.toml
      - name: "Export code coverage"
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.lcov
          verbose: true
```

It looks like you recently worked on a number of scripts surrounding the clarinet testing for sbtc-mini. Do you think getting codecov and clarinet testing within our CI something you could give a quick look?
